### PR TITLE
Setup patch

### LINKED ISSUE #20: MAG setup issues
- `data/external` does not exist
- `mag_orm.py` does not import `psycopg2` and `DuplicateDataBase` should be `DuplicateDatabase`
- `Click` is listed twice in requirements which causes `make requirements` to fail

```
modified   fnf/data/mag_orm.py                                                                                         
@@ -3,6 +3,7 @@ from sqlalchemy.dialects.postgresql import TEXT, VARCHAR, TSVECTOR                                     
 from sqlalchemy import Column, ForeignKey                                                                             
 from sqlalchemy.orm import relationship                                                                               
 from sqlalchemy.types import Integer, Date, Boolean, Float, BIGINT                                                    
+import psycopg2                                                                                                       
                                                                                                                       
 Base = declarative_base()                                                                                             
                                                                                                                       
@@ -162,7 +163,7 @@ if __name__ == "__main__":                                                                         
         conn.execute("create database disinfo")                                                                       
         conn.close()                                                                                                  
     except exc.DBAPIError as e:                                                                                       
-        if isinstance(e.orig, psycopg2.errors.DuplicateDataBase):                                                     
+        if isinstance(e.orig, psycopg2.errors.DuplicateDatabase):                                                     
             logging.info(e)                                                                                           
         else:                                                                                                         
             logging.error(e)                                                                                          
modified   requirements.txt                                                                                            
@@ -24,5 +24,4 @@ retrying==1.3.3                                                                                      
 pytest==5.2.2                                                                                                         
 setuptools==41.4.0                                                                                                    
 requests==2.22.0                                                                                                      
-Click==7.0                                                                                                            
 PyYAML==5.2     
```

- May want to consider a restructure of the repo such that a folder `fnf/mag/` contains all the MAG scripts (depending on what other future analyses are planned for this repo)

### PR DESCRIPTION
**Pull request by kstathou**
Patch some setup issues.

Closes #20

### CODE REVIEW

**Comment by kstathou** [comment]
One of the issues you mentioned @bishax were fixed by #11

**Comment by kstathou** [comment]
I found the issue with the `data/external`; it was only working when I was running the script from the root project dir. `data/external` was used in `parse_mag.py` which is now fixed. Let me know if you find any other issues!

**Comment by bishax** [comment]
I think the underlying problem with `data/external` could be the fault of the cookiecutter.
If you add and commit an empty `.gitkeep` into `data/external` then `git clone` will always create `data/external` even if there is no data in there.

**Comment by kstathou** [comment]
Added it @bishax ! Let me know if I can merge!

**Pull request merged**
